---
- hosts: localhost
  become: true
  roles:
    - geerlingguy.mysql
    - dpalomar.sts
    - geerlingguy.docker
    - franklinkim.mongodb
    - softasap.sa-neo4j
    - jdauphant.sublimetext
    - cmprescott.chrome
    - gantsign.maven